# Generated by Django 4.2.7 on 2023-11-10 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myApp", "0002_admininfo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="admininfo",
            name="adminname",
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name="userinfo",
            name="username",
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
