# Generated by Django 4.2.7 on 2023-11-10 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myApp", "0004_printers_tasks"),
    ]

    operations = [
        migrations.AlterField(
            model_name="printers",
            name="inkVol",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="tasks",
            name="printerID",
            field=models.CharField(max_length=64, null=True),
        ),
    ]
