# Generated by Django 4.2.7 on 2023-11-10 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myApp", "0005_alter_printers_inkvol_alter_tasks_printerid"),
    ]

    operations = [
        migrations.AddField(
            model_name="printers",
            name="printerStatus",
            field=models.CharField(default="空闲", max_length=64),
        ),
    ]
