# Generated by Django 4.2.7 on 2023-11-11 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myApp", "0007_transactions_workerinfo_tasks_money_tasks_submittime"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transactions",
            name="taskID",
        ),
        migrations.RemoveField(
            model_name="transactions",
            name="userID",
        ),
    ]
