# Generated by Django 4.2.7 on 2023-11-11 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myApp", "0009_transactions_transname"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tasks",
            name="printerID",
        ),
    ]
