# Generated by Django 4.2.7 on 2023-11-11 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myApp", "0011_tasks_taskname"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="printers",
            name="inkVol",
        ),
    ]
