# Generated by Django 4.2.7 on 2023-11-12 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myApp", "0012_remove_printers_inkvol"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tasks",
            name="taskName",
        ),
        migrations.AddField(
            model_name="tasks",
            name="fileName",
            field=models.CharField(default="1", max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tasks",
            name="pickCode",
            field=models.CharField(default="1", max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tasks",
            name="taskDescp",
            field=models.CharField(default="1", max_length=128),
            preserve_default=False,
        ),
    ]
