# Generated by Django 4.2.7 on 2023-11-12 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myApp", "0013_remove_tasks_taskname_tasks_filename_tasks_pickcode_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tasks",
            old_name="taskDescp",
            new_name="Descp",
        ),
    ]
