# Generated by Django 4.2.7 on 2023-11-12 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myApp", "0014_rename_taskdescp_tasks_descp"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tasks",
            name="submitTime",
        ),
    ]
