# Generated by Django 4.2.7 on 2023-11-12 14:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("myApp", "0015_remove_tasks_submittime"),
    ]

    operations = [
        migrations.AddField(
            model_name="tasks",
            name="submitTime",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
