# Generated by Django 4.2.7 on 2023-11-12 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myApp", "0016_tasks_submittime"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tasks",
            name="submitTime",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
