# Generated by Django 4.2.7 on 2023-11-12 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myApp", "0019_tasks_fileid_alter_tasks_taskid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tasks",
            name="Descp",
        ),
        migrations.AddField(
            model_name="tasks",
            name="color",
            field=models.CharField(default="1", max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tasks",
            name="doubleSided",
            field=models.CharField(default="1", max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tasks",
            name="note",
            field=models.CharField(default="1", max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tasks",
            name="paper",
            field=models.CharField(default="1", max_length=64),
            preserve_default=False,
        ),
    ]
