# Generated by Django 4.2.7 on 2023-11-16 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0020_remove_tasks_descp_tasks_color_tasks_doublesided_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='printers',
            name='inkVol',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
