# Generated by Django 4.2.7 on 2023-11-16 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0021_printers_inkvol'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='reservedTime',
            field=models.CharField(default='2023-11-16 10:00', max_length=64),
        ),
    ]
