# Generated by Django 4.2.7 on 2023-11-25 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0022_tasks_reservedtime'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transactions',
            options={'verbose_name': '收支管理', 'verbose_name_plural': '收支管理'},
        ),
    ]
