# Generated by Django 4.2.7 on 2023-11-25 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0023_alter_transactions_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='money',
            field=models.FloatField(verbose_name='金额'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='submitTime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='transName',
            field=models.CharField(max_length=64, verbose_name='收支项目'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='transactionID',
            field=models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='项目ID'),
        ),
    ]
