# Generated by Django 4.2.7 on 2023-11-25 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0024_alter_transactions_money_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='printers',
            options={'verbose_name': '打印机管理', 'verbose_name_plural': '打印机管理'},
        ),
        migrations.AlterField(
            model_name='printers',
            name='inkVol',
            field=models.IntegerField(verbose_name='剩余墨量（%）'),
        ),
        migrations.AlterField(
            model_name='printers',
            name='paperVol',
            field=models.IntegerField(verbose_name='剩余纸量（%）'),
        ),
        migrations.AlterField(
            model_name='printers',
            name='printerID',
            field=models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='打印机ID'),
        ),
        migrations.AlterField(
            model_name='printers',
            name='printerName',
            field=models.CharField(max_length=64, verbose_name='打印机名称'),
        ),
        migrations.AlterField(
            model_name='printers',
            name='printerStatus',
            field=models.CharField(default='空闲', max_length=64, verbose_name='状态'),
        ),
    ]
